final dolerme = [
  "Por todas esas veces que me puse detrás",
  "Y yo cambié lo mío por lo que tú querías",
  "Por todas esas veces que me puse detrás",
  "Y yo cambié lo mío por lo que tú querías",
  "Esas bixis que ahora tienes baby, no saben que",
  "Esas bixis que ahora tienes baby, no saben que",
  "Lo que les espera, lo que les espera, lo que les espera",
  "Yo ya no sé por qué no quiere dolerme",
  "Acelero pa' ve' si consigo estrellarme",
  "Quiero que lo veas y no pienses en detenerme",
  "Y así demuestras que has podido olvidarme",
  "¿O por qué no pones tú también de tu parte?",
  "Pisa a fondo y deja ir el volante",
  "Que no tenga que ir yo una vez más a buscarte",
  "Porque sé que no podrás atreverte",
  "Deprisa, deprisa, deprisa",
  "Que no sea mañana",
  "Me parto la camisa",
  "Deprisa, deprisa, deprisa",
  "Que no sea mañana",
  "Que no sea mañana",
  "Yo ya no sé por qué no quiere dolerme",
  "Acelero pa' ve' si consigo estrellarme",
  "Quiero que lo veas y no pienses en detenerme",
  "Así demuestras que has podido olvidarme",
  "¿O por qué no pones tú también de tu parte?",
  "Pisa a fondo y deja ir el volante",
  "Que no tenga que ir yo una vez más a buscarte",
  "Porque sé que no podrás atreverte",
  "Yo ya no sé por qué no quiere dolerme",
  "Yo ya no sé por qué no quiere dolerme",
];
final deAquiNoSales = [
  "Yo que tanto te camelo",
  "Y tú me das pie",
  "Haciendo que tú de aquí no sales",
  "Mucho más a mí me duele",
  "De lo que a ti te está doliendo",
  "Conmigo no te equivoques",
  "Con el revés de la mano",
  "Yo te lo dejo bien claro",
  "Amargas penas te vendo",
  "Caramelos también tengo",
];
final linda = [
  "¿Qué haces, tía?",
  "Hay un teteo ahorita en un callejón con kitipó",
  "¿Ah sí, quieres ir?",
  "Vamo' a chulearno' pa' allá (jajajaja, jajajaja)",
  "Llegué tarde a la cita, estaba con La ROSALÍA",
  "Las amigas que se besan son la mejor compañía",
  "hoy estoy a fuego, 'toy chucky",
  "Dulce, deliciosa como una cookie",
  "Hoy estoy a fuego, 'toy chucky",
  "Dulce, deliciosa como una cookie",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Llegué tarde, salí pa' donde ti, pero terminé en un teteo",
  "Después me fui pa' un punto a bregar con un capeo",
  "Siempre llego tarde, me coge el tiempo singando",
  "Tengo una negra en casa que siempre tiene gana'",
  "Llegué tarde a la cita, estaba con La ROSALÍA",
  "Las amigas que se besan son la mejor compañía",
  "Llegué tarde a la cita, estaba con La ROSALÍA",
  "Las amigas que se besan son la mejor compañía (compañía)",
  "Muévetelo como e', Tokischa y ROSALÍA",
  "Ella hace arro' con habichuela y yo le enrolo la María",
  "Sabe mejor que los tre' golpe, yo me la como to' lo' día'",
  "Que yo le canto por bachata y ella me canta por bulería",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Le tiro un besito a la mami que me disfruta",
  "Le muerdo el cachete como si fuera una fruta",
  "Siempre llego tarde porque me invento la ruta",
  "Le escupo la cara al tiempo como si fuera mi puta",
  "Pa' quita'me la arrechura y desacato tengo tiempo",
  "Poniéndome la prenda pa' tirarme por el bloque",
  "Calentura vaginal de R.D. pa' Barcelona",
  "La reina' de esta popola, tenemo' la corona",
  "Las dura' de las dura' de eso ya no e' un secreto",
  "Las uñas en punta, las llevamos stiletto",
  "Uy, Toki', estoy enamorada",
  "Uy, Toki', tú eres de respeto",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Tú ere' linda y yo estoy rulin",
  "Nos besamo', pero somo' homie'",
  "Uy, Toki', Toki', Toki', Toki'",
  "Toki', Toki', Toki', Toki'",
  "Toki', Toki', Toki', Toki'",
  "Toki', Toki', Toki', Toki'",
];
final laNocheDeAnoche = [
  "Yo sé que esto no volverá a pasar",
  "Pero si volviera a pasar",
  "Sé que sería tu debilidad",
  "Porque la noche de anoche fue (-ue)",
  "Algo que yo no puedo explicar",
  "Sola, dando y dándole sin parar (-rar)",
  "Tú me decías que morías por mí",
  "Porque la noche de anoche fue (eh eh)",
  "Algo que yo no puedo explicar (eh eh)",
  "Eso era dando y dándole sin parar",
  "Tú encima de mí, yo encima de ti (oh oh)",
  "Eh, eh",
  "Tú me dejaste el cuerpo caliente, infierno",
  "Pero me dejaste el corazón frío, invierno",
  "Soñando que contigo es que duermo (duermo)",
  "Dime, papi",
  "Dime, mami",
  "¿Esa noche quién la borra?",
  "Tú me besaste y se me cayó la gorra",
  "Sin mucha labia, sin mucha cotorra",
  "Cuando estoy contigo dejo que la vibra corra",
  "Y que la luna nos supervise",
  "Con esa boquita suena rico todo lo que tú me dices",
  "Hicimos poses que yo más nunca hice",
  "Tú te mojaste pa que yo me bautice",
  "Y me ponga serio, serio",
  "Tú y yo juntos creando un imperio",
  "Esos ojitos tienen un misterio",
  "Pero al final nada de lo nuestro fue en serio",
  "Y ya me ha pasao que me han ilusionao",
  "Y ya me ha pasao que me han abandonao",
  "Y ya me ha pasao que no estás a mi lao",
  "Y ya me ha pasao",
  "Porque la noche de anoche fue (eh eh)",
  "Algo que yo no puedo explicar (eh eh)",
  "Eso era dando y dándole sin parar (eh eh)",
  "Tú encima de mí, yo encima de ti (oh oh)",
  "Porque la noche de anoche fue (eh eh)",
  "Algo que yo no puedo explicar (eh eh)",
  "Sola, dando y dándole sin parar (eh eh)",
  "Yo encima de ti, tú encima de mí (oh oh)",
  "Que yo me iría otra vez pa Japón (hey)",
  "Papi, qué penita tú, qué maldición (mmm)",
  "La paleta es dulce, azúcar de algodón (yeh)",
  "Y es la única que me llega hasta al corazón",
  "Yo no me olvido, la suerte está echada (bum)",
  "Se me enredaba el pelo en la pantalla",
  "Sabes que solo lo hago de leyenda (¡wuh!)",
  "Lo subo al cielo, yo soy su messiah",
  "El benito es un diablillo, ella es un ángel",
  "Lo tengo juqueao como si fuera tote",
  "Baby, entre nosotros nunca competimos",
  "Si preguntan dice, ella todos los récords bate",
  "Y ya me ha pasao que me han ilusionao",
  "Y ya me ha pasao que me han abandonao",
  "Y ya me ha pasao que no estás a mi lao",
  "Y ya me ha pasao",
  "Porque la noche de anoche fue (eh eh)",
  "Algo que yo no puedo explicar (eh eh)",
  "Eso era dando y dándole sin parar (eh eh)",
  "Tú encima de mí, yo encima de ti (oh oh)",
  "Porque la noche de anoche fue (eh eh)",
  "Algo que yo no puedo explicar (eh eh)",
  "Eso era dando, dándole sin parar (eh eh)",
  "Tú encima de mí, yo encima de ti (oh oh)",
  "Mmm jum",
  "Mmm",
  "Mmm, jum",
];
final piensoEnTuMira = [
  "Me da miedo cuando sales",
  "Sonriendo pa' la calle",
  "Porque todos pueden ver",
  "Los hoyuelitos que te salen",
  "Y del aire cuando pasa",
  "Por levantarte el cabello",
  "Y del oro que te viste",
  "Por amarrarse a tu cuello",
  "Y del cielo y de la luna",
  "Porque tú quieras mirarlo",
  "Hasta del agua que bebes",
  "Cuando te mojas los labios",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá",
  "Pienso en tu mirá",
  "Me da miedo cuando sales",
  "Sonriendo pa' la calle",
  "Porque todos pueden ver",
  "Los hoyuelitos que te salen",
  "Me da miedo cuando sales",
  "Sonriendo pa' la calle",
  "Porque todos pueden ver",
  "Los hoyuelitos que te salen",
  "Tan bonita que amenaza",
  "Cuando callas me das miedo",
  "Tan fría como la nieve",
  "Cuando cae desde el cielo",
  "Cuando sales por la puerta",
  "Pienso que no vuelves nunca",
  "Y si no te agarro fuerte",
  "Siento que será mi culpa",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pe'",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pe'",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá, tu mirá clavá es una bala en el (pienso en tu mirá, pienso en tu mirá)",
  "Pienso en tu mirá, tu mirá clavá es una bala en el pecho",
  "Pienso en tu mirá",
  "Pienso en tu mirá",
  "Me da miedo cuando sales",
  "Sonriendo pa' la calle",
  "Porque todos pueden ver",
  "Los hoyuelitos que te salen",
  "Me da miedo cuando sales",
  "Sonriendo pa' la calle",
  "Porque todos pueden ver",
  "Los hoyuelitos que te salen",
];
final perdoname = [
  "Mami, yo sé que no estás bien",
  "Y piensas que ya te dejé de querer, estás equivocada",
  "Yo lo sé, que fallé porque fui infiel la noche de ayer",
  "Siempre me arrepentiré, y de rodillas te pido, mujer",
  "Si alguna vez sentiste algo lindo por mí",
  "Perdóname, perdóname",
  "Si alguna vez sentiste algo lindo por mí",
  "Perdóname, perdóname, mujer (perdonamé)",
  "Mami, yo sé quе no estás bien",
  "Y piensas quе ya te dejé de querer, estás equivocada",
  "Yo lo sé, que fallé porque fui infiel la noche de ayer",
  "Siempre me arrepentiré, y de rodillas te pido, mujer",
  "Si alguna vez sentiste algo lindo por mí",
  "Perdóname, perdóname",
  "Si alguna vez sentiste algo lindo por mí",
  "Perdóname, perdóname, mujer (perdonamé)",
];
final dePlata = [
  "Cuando yo",
  "Cuando yo me...",
  "Me muera",
  "Te pi'o un encargo",
  "Que con tus trenzas",
  "Que trenzas de tu pelo negro",
  "Me 'marren mis manos",
  "Ay, si el querer",
  "El que yo te tengo",
  "Si de plata fuera",
  "El querer",
  "El que yo te tengo",
  "Si de plata fuera",
  "Otro más rico, más rico que yo",
  "Ay, en la España aún hubiera",
];
final laRelacionRemix = [
  "Ahora todo cambió, le toca a ella",
  "Latino gang",
  "Ayer la vi perreando solita",
  "Se ve má bonita",
  "Ahora que no está con ese man",
  "Que la felicidad como ropa se la quita",
  "Ella siempre estaba cuando tú no estabas",
  "Fue tanto dolor que ya no la mataba",
  "Poco a poco, ya no te necesitaba",
  "Ella sonreía mientras lo enrolaba",
  "Y tú",
  "Diciendo que fue falta de actitud",
  "Pero en esta relación hizo más que tú, yeah",
  "Y en un estado te manda a decir que",
  "Ahora todo cambió, le toca a ella",
  "Mari y una botella",
  "Gracias al maltrato se puso bella",
  "Ahora tú la quiere' y no te quiere ella",
  "Y ahora todo cambió, le toca a ella",
  "Mari y una botella",
  "Gracias al maltrato se puso bella",
  "Ahora tú la quiere' y no te quiere ella, yeh, uh",
  "Cambió, cambió, y tú estas pagando",
  "Se fue el balón y quieres seguir jugando (¿Cómo?)",
  "Mientras lloraba, tú estabas tomando",
  "Ahora estás llamando y ella se está cambiando",
  "Que va pa' la calle",
  "Sin dar detalle'",
  "Con ese traje yo dudo que ella falle",
  "Siempre linda, con o sin maquillaje",
  "Siempre en línea, automático el mensaje que",
  "Ahora todo cambió, le toca a ella",
  "Mari y una botella",
  "Gracias al maltrato se puso bella",
  "Ahora tú la quiere' y no te quiere ella",
  "Y ahora todo cambió, le toca a ella",
  "Mari y una botella",
  "Gracias al maltrato se puso bella",
  "Ahora tú la quiere' y no te quiere ella",
  "Y ahora todo cambió, comenzó por su estado",
  "Ahora te toca esperarla sentado",
  "Cambió de número pa' que usted ni piense en llama'",
  "Te toca extrañarla na' má'",
  "Ya jugó tú número",
  "Y también borró tú número",
  "Prendió uno y te superó",
  "Le pusieron la canción y gritó: ¡Súbelo!",
  "Ella siempre estaba cuando tú no estabas",
  "Fue tanto dolor que ya no la mataba",
  "Poco a poco, ya no te necesitaba",
  "Ella sonreía mientras lo enrolaba",
  "Y tú",
  "Diciendo que fue falta de actitud",
  "Pero en esta relación hizo más que tú, yeah (Yeh-eh)",
  "Y en un estado te manda a decir que",
  "Ahora todo cambió, le toca a ella",
  "Mari y una botella",
  "Gracias al maltrato se puso bella",
  "Ahora tú la quiere' y no te quiere ella",
  "Y ahora todo cambió, le toca a ella",
  "Mari y una botella",
  "Gracias al maltrato se puso bella",
  "Ahora tú la quiere' y no te quiere ella",
  "Dímelo Flow",
  "Slow, Mike",
  "Este es Sech",
  "Rich Music",
  "El Bloke",
  "1964, alright?",
];
final tkn = [
  "Cosa' de familia, no la' tienen que escucha'",
  "Lo' capo' con lo' capo' y yo soy la mamá",
  "Los secreto' solo con quien pueda' confia'",
  "Más-más te vale no romper la omertá",
  "Hay nivele' para todo en esta vi'a",
  "No jodemo' con persona' desconoci'a'",
  "Ni un amigo nuevo, ni uno haría",
  "Ni un amigo nuevo, ni uno haría",
  "TKN, TKN, TKN",
  "Ni un amigo nuevo, ni uno haría",
  "TKN, TKN",
  "Ni un amigo nuevo, ni uno haría",
  "Zoom en la cara, Gaspar Noé",
  "E'to no dispara', la vacié",
  "VVS, VVS, Dolce Vita",
  "Mi mando está duro, dinamita",
  "Tatua' de pie' hasta la nuca",
  "Vestia' de negro como Kika",
  "VVS, VVS, Dolce Vita (VVS)",
  "El mando está duro, dinamita",
  "Leche con azúcar",
  "Ella tiene medida' brazuca'",
  "Esa mami es una G (Yeah)",
  "She got hips I gotta grip for (Yeah)",
  "A lot of ass, don't need to have more",
  "I know it's sweet, I like that",
  "Mmm-mmm (Straight up)",
  "I got word that it's wet, well, let's drown",
  "Toot it up, back it up, slap it down",
  "Don't say a word of what you heard from when I came around (It's lit)",
  "You get it first, you get this work right when you come in town (Yeah)",
  "Need you right here (Yeah)",
  "Know you the queen of givin' ideas",
  "No more new friends, don't bring the hype here (Ooh)",
  "Know you got problems with this, but it's not fair",
  "Cosa' de familia, no la' tienen que escucha'",
  "Lo' capo' con lo' capo' y yo soy la mamá (El papá)",
  "Los secreto' solo con quien pueda' confia'",
  "Más-más te vale no romper la omertá",
  "TKN, TKN, TKN",
  "TKN, TKN",
  "Ni un amigo nuevo, ni uno haría'",
  "La Rosalía",
  "Straight up!",
  "Ni un amigo nuevo, ni uno haría'",
];
final yoXTiTuXMi = [
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí, hmm-hmm, hmm-hmm",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí (Woh, oh, oh; pongan lo' grillete')",
  "Mami",
  "Colgando del cuello los juguete' (Del cuello los juguete')",
  "Rodea' de flores y billete' (De flores y billete')",
  "'Tamos Worldwide a machete (Sí, sí)",
  "Y mira, \"bang-bang\" si con nosotro' te entromete' (Pa-pa-pa), eh",
  "No quieres que lo aprete (Yeah)",
  "Me da igual si tu amor me compromete' (Nah; me da igual)",
  "Contigo apuesto to' al número siete (Siete, siete)",
  "Si me caigo, que tú me sujete' (Eh, please)",
  "Yo por ti, tú por mí, que me pongan los grillete' (Los grillete')",
  "Somos dos cantantes como los de ante'",
  "El respeto es en boletos y diamante'",
  "Se me para el cora' sólo con mirarte",
  "Porque a ti te canto pa' que tú me cante'",
  "Somos dos cantantes como los de antes",
  "El respeto en boletos y diamante'",
  "Se me para el cora' sólo con mirarte",
  "Porque a ti te canto pa' que tú me cante'",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí, hmm-hmm, hmm-hmm",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí (Ponga lo' grillete')",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí, hmm-hmm, hmm-hmm",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí (Ponga lo' grillete')",
  "Y yo por ti, tú por mí, ¿quién lo diría? (Woh, oh, oh)",
  "Eres única, mamacita Rosalía (Rosalía)",
  "Tiene' el poder que mi mente desvía (Desvía)",
  "Yo por ti por ahí me tiraría",
  "Tiene' lo que otra' no tenía' (Woh, oh)",
  "Muy diferente a lo que de ti me decían (Woh, oh)",
  "Choqué con tu química, qué suerte la mía (Woh, oh)",
  "Lo que tengo lo gastaría porque tus ojos, ma'i, brillarían",
  "Y es que, ¿quién lo diría",
  "Que hasta en la esquina esta sazón sonaría?",
  "Choqué con tu química, qué suerte la mía",
  "Lo que tengo lo gastaría porque tus ojos, ma'i, brillarían, yeah",
  "Somos dos cantantes como los de ante'",
  "El respeto es en boletos y diamante'",
  "Se me para el cora' sólo con mirarte",
  "Porque a ti te canto pa' que tú me cantes",
  "Somos dos cantantes como los de ante'",
  "El respeto en boletos y diamante'",
  "Se me para el cora' sólo con mirarte",
  "Porque a ti te canto pa' que tú me cantes",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí, hmm-hmm, hmm-hmm",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí (Ponga lo' grillete')",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí, hmm-hmm, hmm-hmm",
  "Yo por ti, tú por mí, yo por ti, tú por mí",
  "Yo por ti, tú por mí (Ponga lo' grillete')",
  "Yo por ti, tú por mí, yo por ti, tú por mí (Que me pongan lo' grillete')",
  "Yo por ti, tú por mí, hmm-hmm, hmm-hmm (Que me pongan lo' grillete')",
  "Yo por ti, tú por mí, yo por ti, tú por mí (Que me pongan lo' grillete')",
  "Yo por ti, tú por mí",
  "La Rosalía",
  "Mira, ¿quién lo diría (¿Qué?)",
  "Que hasta en la esquina esta sazón sonaría? (Ozuna)",
  "¿Quién lo diría que hasta en la esquina esta sazón sonaría por ti?",
  "¿Quién lo diría que hasta en la esquina esta sazón sonaría por ti? (Hmm)",
  "¿Quién lo diría? (Hmm)",
];
final despecha = [
  "Yeah-yeah",
  "Yeah-yeah",
  "Mmm",
  "Baby, no me llame'",
  "Que yo estoy ocupá' olvidando tus male'",
  "Ya decidí que esta noche se sale",
  "Con toda' mis motomami', con toda' mis gyale'",
  "Y ando despechá', oah, alocá'",
  "Bajé con un flow nuevo de caja, baby, hackeá'",
  "Lo muevo de la'o a la'o y a otro la'o",
  "Hoy salgo con mi baby de la disco coroná'",
  "Y ando despechá', oah, alocá'",
  "Que Dios me libre de volver a tu la'o",
  "Lo muevo de la'o a la'o y a otro la'o",
  "Hoy salgo con mi baby de la disco coroná', coroná', yeah",
  "Voy con la falda (ah), aro' y cadena' (eh)",
  "Piña colada (sí), no tengo pena (no)",
  "'Toy con la Fefa (wuh), ella es la jefa (sí)",
  "Ella lo baila (yeh), ella me enseña (yeh)",
  "Hoy no trabaja (uh) esta morena (no)",
  "Fuck la fama (eh), fuck la faena (ja)",
  "La noche es larga (eh), la noche está buena (eh)",
  "Un mambo violento y fin del problema",
  "Mira qué fácil te lo v'y a decir",
  "A, B, C, one, two, three",
  "Mira qué fácil te lo v'y a decir",
  "Que esta motomami ya no está pa' ti",
  "Mira qué fácil te lo v'y a decir",
  "A, B, C, one, two, three",
  "Mira qué fácil te lo v'y a decir",
  "Que esta motomami ya -",
  "Y ando despechá', oah, alocá'",
  "Bajé con un flow nuevo de caja, baby, hackeá'",
  "Lo muevo de la'o a la'o y a otro la'o",
  "Hoy salgo con mi baby de la disco coroná'",
  "Y ando despechá', oah, alocá'",
  "Que Dios me libre de volver a tu la'o",
  "Lo muevo de la'o a la'o y a otro la'o",
  "Hoy salgo con mi baby de la disco coroná', coroná', yeah",
  "Mmm, voy a 180 porque soy una racineta, ¿qué, qué?",
  "Te distrae' y yo te adelanto por la derecha, uh",
  "Voy a 180 porque soy una racineta, ey, ey",
  "Te distrae' y yo te adelanto por la derecha, mmm, mmm, mmm",
  "Yeah-yeah-yeah-yeah-yeah-yeah",
  "Ey",
  "Yeah-yeah-yeah-yeah",
  "Chris Jedi",
  "Gaby, Gaby, Gaby",
  "De Barcelona pa' Santo Domingo",
  "La ROSALÍA, mmm, jaja, je",
  "Jeje",
  "Ey",
  "Uh, uh, uh, uh",
  "Omega",
  "Ey, ey, ey",
  "Uh, uh, uh, uh",
];
final aislamiento = [
  "Salgo del hotel, me acompañan tre'",
  "Hoodie y las gafa' y así nadie me ve",
  "Me creo invisible, escucho el \"tic-toc\"",
  "De golpe die' flash y el cora acelera'o",
  "Me acerco a la prensa, salimo' pisa'o",
  "TMZ detrá', lo dejamo' atrá'",
  "Gucci flip-flops, chequeo the opps",
  "Llueve sobre el top, se resbalan como teardrops",
  "\"La Japonaise\", Claude Monet",
  "Si está feli', yo no lo sé",
  "Cuchillos que cortan satén",
  "When they pull up, las cámaras shooting like \"pa-pa-pa-pa\"",
  "Oh, yeah",
  "When they pull up, las bitches 'tán trippin' like \"yah-yah-yah-yah\"",
  "Oh, yeah",
  "Lo que tú nunca ves, que",
  "Se acaba la escena, cae mi melena",
  "Es el imperio el que destruye",
  "La emperatriz que lo construye",
  "Parece que se parte el cielo, pero no importa",
  "Soy joven, bonita, soy triste y",
  "Salgo del hotel, me acompañan tre'",
  "Hoodie y las gafa' y así nadie me ve",
  "Me creo invisible, escucho el \"tic-toc\"",
  "De golpe' die' flash y el cora acelera'o",
  "Sola en el Mirage, voy sin entourage",
  "Me creo que el mundo es mío",
  "Si me sale una lágrima, Dios me lo perdone",
  "Por dar por senta'o tanta' bendicione'",
  "When they pull up, las cámaras shooting like \"pa-pa-pa-pa\"",
  "Oh, yeah",
  "When they pull up, las bitches 'tán trippin' like \"yah-yah-yah-yah\"",
  "Oh, yeah",
  "Lo que tú nunca ves, que",
  "Se acaba la escena, cae mi melena",
  "Es el imperio el que destruye",
  "La emperatriz que lo construye",
  "Parece que se parte el cielo, pero no importa",
  "Soy joven, bonita, soy triste y brillante",
];
final bindingLightsRemix = [
  "Yeah",
  "Yo intenté llamar",
  "Llevo mucho sola, la verdad",
  "Maybe tú me enseñas cómo amar",
  "Maybe",
  "Ya no consumo na' (na', na')",
  "Y tú no tendrás que hacer too much",
  "Si me rozas ya me encenderás",
  "Bebé",
  "I look around and",
  "Sin City's cold and empty (oh)",
  "No one's around to judge me (oh)",
  "I can't see clearly when you're gone",
  "I said, ooh, I'm blinded by the lights",
  "No, I can't sleep until I feel your touch",
  "I said, ooh, I'm drowning in the night",
  "Oh, when I'm like this, you're the one I trust",
  "Hey, hey, hey",
  "I'm running out of time",
  "'Cause I can see the sun light up the sky",
  "So I hit the road in overdrive, baby, oh",
  "The city's cold and empty (oh)",
  "No one's around to judge me (oh)",
  "I can't see clearly when you're gone",
  "I said, ooh, I'm blinded by the lights",
  "No, I can't sleep until I feel your touch",
  "I said, ooh, I'm drowning in the night",
  "Oh, when I'm like this, you're the one I trust",
  "Y en verdad yo te volví a llamar (back to let you know)",
  "Porque tengo algo que contar (say it on the phone)",
  "No te voy a soltar this time (ooh)",
  "I said, ooh, I'm blinded by the lights",
  "No, I can't sleep until I feel your touch",
  "Hey, hey, hey",
  "Hey, hey, hey",
  "Y llega, duermo con la luz abierta",
  "Esperando pa' que vengas",
  "Prefiero 'tar a tu vera",
  "Y llega, duermo con la luz abierta",
  "Esperando pa' que vengas",
  "Prefiero 'tar a tu vera",
  "I said, ooh, I'm blinded by the lights",
  "No, I can't sleep until I feel your touch",
];
final dineroYLibertad = [
  "To' el mundo quiere fortuna, dinero y libertad",
  "Pero pedirte a ti no está de más",
  "He encontra'o razone', he mira'o la luna",
  "Señas del destino, no sobra ninguna",
  "Y mentirte, ¿pa' qué?, hice un salto de fe",
  "Tú te esperaste por mi firma debajo 'el Mercer",
  "Que me perdone el que yo piense que está a mi merced",
  "A mi manera por el mundo, no es que sea de mala fe",
  "Y yo duermo con el hoodie que me habías hecho, eh",
  "Lleva mi nombre pinta'o en el pecho",
  "Quería dormir y me han roba'o el sueño",
  "Ahora dime",
  "Ya estás engancha'o, soy heroína",
  "Tú 'tás juquea'o (Mmm), soy cocaína (Mmm)",
  "La calle está enamorá', enamorada de mí",
  "Y yo estoy enamorá', enamorá' de la calle",
  "No me moleste' los canto', que te los canta Jarillo",
  "Como Canelita, por rumba que por tanguillo",
  "Aquí, dejaste aquí",
  "Yo a lo kitty chiri",
  "Con mis cadena', yo a lo kitty chiri",
  "Con mis cadena', yo a lo kitty chiri",
  "¡Wuh!",
  "Ya estás engancha'o, soy heroína",
  "Tú 'tás juquea'o, soy cocaína",
  "La calle está enamorá', enamorada de mí",
  "Y yo estoy enamorá', enamorá' de la calle",
  "La calle está enamorá', enamorada de mí",
  "Y yo estoy enamorá', enamorá' de la calle",
];
final malamente = [
  "Ese cristalito roto",
  "Yo sentí como crujía",
  "Antes de caerse al suelo",
  "Ya sabía que se rompía (uh)",
  "Está parpadeando",
  "La luz del descansillo",
  "Una voz en la escalera",
  "Alguien cruzando el pasillo",
  "Malamente (eso es; así si)",
  "Malamente (¡tra, tra!)",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal (mira)",
  "Malamente (toma que toma)",
  "Está en la mente (eso es; ¡illo!)",
  "Malamente",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal",
  "Malamente (uh)",
  "Se ha puesto la noche rara",
  "Han sali'o luna' y estrella' (eh)",
  "Me lo dijo esa gitana (¿qué?)",
  "Mejor no salir a verla (no)",
  "Sueño que estoy andando",
  "Por un puente y que la acera (mira, mira, mira, mira)",
  "Cuanto más quiero cruzarlo (va)",
  "Más se mueve y tambalea",
  "Malamente (eso es; así si)",
  "Malamente (¡tra, tra!)",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal (mira)",
  "Malamente (toma que toma)",
  "Está en la mente (eso es; ¡illo!)",
  "Malamente",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal",
  "Malamente",
  "Aunque no esté bonita",
  "La noche undivé",
  "Voy a salir pa la calle",
  "En la manita los aro' brillando, en mi piel los corale'",
  "Me protejan, me salven",
  "Me iluminen, me guarden",
  "Y por delante",
  "No voy a perder ni un minuto en volver a pensarte",
  "Malamente (eso es; así si)",
  "Malamente (¡tra, tra!)",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal (mira)",
  "Malamente (toma que toma)",
  "Está en la mente (eso es; ¡illo!)",
  "Malamente",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal (illo)",
  "Malamente (toma que toma)",
  "Está en la mente (¡illo!)",
  "Malamente (¡tra, tra!)",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal",
  "Malamente (toma que toma)",
  "Está en la mente (eso es; ¡illo!)",
  "Malamente",
  "Mal, mu' mal, mu' mal, mu' mal, mu' mal",
  "Malamente",
];
final conAltura = [
  "Esto vamo' a arrancarlo con altura",
  "El dembow lo canto con hondura",
  "Dicen una estrella, una figura",
  "De Hector aprendí la sabrosura",
  "Nunca viste una joya tan pura",
  "Esto es pa' que quede, lo que yo hago dura (Con altura)",
  "Demasiada' noches de travesura' (Con altura)",
  "Vivo rápido y no tengo cura (Con altura)",
  "Iré joven pa' la sepultura (Con altura)",
  "Esto es pa' que quede, lo que yo hago dura (Con altura)",
  "Demasiada' noches de travesura' (Con altura)",
  "Vivo rápido y no tengo cura (Con altura)",
  "Iré joven pa' la sepultura (Con altura)",
  "Pongo rosas sobre el Panamera",
  "Pongo palmas sobre la guantanamera",
  "Llevo a Camarón en la guantera (De la Isla)",
  "Lo hago para mi gente y lo hago a mi manera",
  "Flores azules y quilates y si es mentira que me maten",
  "Flores azules y quilates y si es mentira que me maten",
  "(Con altura)",
  "(Con altura)",
  "Esto es pa' que quede, lo que yo hago dura (Con altura)",
  "Demasiada' noches de travesura' (Con altura)",
  "Vivo rápido y no tengo cura (Con altura)",
  "Iré joven pa' la sepultura (Con altura)",
  "Esto es pa' que quede, lo que yo hago dura (Con altura)",
  "Demasiadas noches de travesura' (Con altura)",
  "Vivo rápido y no tengo cura (Con altura)",
  "Iré joven pa' la sepultura (Con altura)",
  "Aquí en la altura están fuertes los vientos",
  "Ponte el cinturón y coge asiento",
  "A tu jeva ya la vi por dentro (Yes)",
  "El dinero nunca pierde tiempo (No, no)",
  "Contra la pared (Tú lo sabe)",
  "Y le tuve que comprar un trago porque la tenías con sed",
  "Desde acá qué rico se ve",
  "No soy de acá pero rompí el bajo otra vez",
  "Y si es mentira que me maten (J Balvin)",
  "Flores azules y quilates",
  "Y si es mentira que me maten",
  "(Con altura)",
  "(Con altura)",
  "Esto es pa' que quede, lo que yo hago dura (Con altura)",
  "Demasiadas noches de travesura' (Con altura)",
  "Vivo rápido y no tengo cura (Con altura)",
  "Iré joven pa' la sepultura (Con altura)",
  "Esto es pa' que quede, lo que yo hago dura",
  "(Siempre dura dura) (Con altura)",
  "Demasiadas noches de travesura' (Con altura)",
  "Vivo rápido y no tengo cura (Con altura)",
  "Iré joven pa' la sepultura (Con altura)",
  "J Balvin",
  "La Rosalía",
  "Vamo', vamo'",
  "Va' va' vamos a perrear (Pa' que quede)",
  "Va' va' vamos a perrear (Pa', pa' que quede)",
  "Va' va' vamos a perrear (Pa' que quede)",
  "Pa' que se dembuque, vamo', vamo'",
  "Lo que yo ahogo, dura",
  "Vamo'",
  "Va' va' vamos a perrear (Pa'que quede)",
  "Va' va' vamos a perrear (Pa', pa' que quede)",
  "Va' va' vamos a perrear (Pa' que quede)",
  "Pa' que se dembuque, vamo' vamo'",
  "Lo que yo hago, dura",
];
